server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    url: jdbc:postgresql://localhost:5432/shareit
  sql:
    init:
      mode:
        always
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    clear-checksums: true

logging:
  level:
    org:
      springframework:
        orm:
          jpa: INFO
          JpaTransactionManager: DEBUG
        transaction:
          INFO
        interceptor: TRACE
