-- liquibase formatted sql

-- changeset Ильнур:1754233057499-1
CREATE SEQUENCE IF NOT EXISTS bookings_seq START WITH 1 INCREMENT BY 50;

-- changeset Ильнур:1754233057499-2
CREATE SEQUENCE IF NOT EXISTS item_requests_seq START WITH 1 INCREMENT BY 50;

-- changeset Ильнур:1754233057499-3
CREATE SEQUENCE IF NOT EXISTS user_sequence START WITH 1 INCREMENT BY 10;

-- changeset Ильнур:1754233057499-4
CREATE TABLE IF NOT EXISTS bookings
(
    id         BIGINT       NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_date   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    item_id    BIGINT       NOT NULL,
    booker_id  BIGINT       NOT NULL,
    status     VARCHAR(255) NOT NULL,
    CONSTRAINT pk_bookings PRIMARY KEY (id)
);

-- changeset Ильнур:1754233057499-5
CREATE TABLE IF NOT EXISTS comments
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text    VARCHAR(255)                            NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    user_id BIGINT                                  NOT NULL,
    item_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_comments PRIMARY KEY (id)
);

-- changeset Ильнур:1754233057499-6
CREATE TABLE IF NOT EXISTS item_requests
(
    id           BIGINT NOT NULL,
    requester_id BIGINT NOT NULL,
    description  VARCHAR(100),
    created      date,
    CONSTRAINT pk_item_requests PRIMARY KEY (id)
);

-- changeset Ильнур:1754233057499-7
CREATE TABLE IF NOT EXISTS items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(50)                             NOT NULL,
    description  VARCHAR(250),
    is_available BOOLEAN                                 NOT NULL,
    owner_id     BIGINT,
    request_id   BIGINT,
    CONSTRAINT pk_items PRIMARY KEY (id)
);

-- changeset Ильнур:1754233057499-8
CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT       NOT NULL,
    name  VARCHAR(55)  NOT NULL,
    email VARCHAR(255) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- changeset Ильнур:1754233057499-9
ALTER TABLE items
    ADD CONSTRAINT uc_items_name UNIQUE (name);

-- changeset Ильнур:1754233057499-10
ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

-- changeset Ильнур:1754233057499-11
ALTER TABLE bookings
    ADD CONSTRAINT FK_BOOKINGS_ON_BOOKER FOREIGN KEY (booker_id) REFERENCES users (id);

-- changeset Ильнур:1754233057499-12
ALTER TABLE bookings
    ADD CONSTRAINT FK_BOOKINGS_ON_ITEM FOREIGN KEY (item_id) REFERENCES items (id);

-- changeset Ильнур:1754233057499-13
ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_ITEM FOREIGN KEY (item_id) REFERENCES items (id);

-- changeset Ильнур:1754233057499-14
ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

-- changeset Ильнур:1754233057499-15
ALTER TABLE items
    ADD CONSTRAINT FK_ITEMS_ON_OWNER FOREIGN KEY (owner_id) REFERENCES users (id);

-- changeset Ильнур:1754233057499-16
ALTER TABLE items
    ADD CONSTRAINT FK_ITEMS_ON_REQUEST FOREIGN KEY (request_id) REFERENCES item_requests (id);

-- changeset Ильнур:1754233057499-17
ALTER TABLE item_requests
    ADD CONSTRAINT FK_ITEM_REQUESTS_ON_REQUESTER FOREIGN KEY (requester_id) REFERENCES users (id);

